/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py:563: UserWarning: This DataLoader will create 40 worker processes in total. Our suggested max number of worker in current system is 20, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
{'CropOrPad': {'target_shape': [224, 256, 1]},
 'Normalization': {'RescaleIntensity': {'out_min_max': [-1, 1],
                                        'percentiles': [1, 99]}},
 'RandomAffine': None,
 'RandomBiasField': None,
 'RandomBlur': None,
 'RandomElasticDeformation': None,
 'RandomGhosting': None,
 'RandomMotion': None,
 'SkipAugmentationProbability': None,
 'batch_size': 6,
 'callback_log_images_freq': 100,
 'callback_log_model_freq': 1,
 'criterion': 'DiceLoss',
 'dataset_dir': '/hpcfs/users/a1787848/MRI_research/data/data_organized_1year',
 'device': 'cpu',
 'early_stopping': 50,
 'encoder_name': 'efficientnet-b7',
 'encoder_weights': 'imagenet',
 'epochs': 2000,
 'include_T1': False,
 'learning_rate': 0.001,
 'log_dce_loss': 10,
 'log_images': False,
 'loss_criterion': {'beta': 0.7, 'loss_function': 'FBetaLoss'},
 'min_val_loss': 0.25,
 'model_dir': '/hpcfs/users/a1787848/MRI_research/mproj7205_hpc/data/saved_models',
 'model_name': 'apricot-sweep-1.pt',
 'network_name': 'UNet',
 'optimizer': 'sgd',
 'project_name': 'project_name',
 'random_split': False,
 'valid_batch_size': 6,
 'verbose': True,
 'workers': 40}
Training on device:cpu
include_T1=False, creating 1C dataset
Dataset size: 168 subjects
Training set: 134 subjects
Validation set: 34 subjects
23
criterion selected: FBetaLoss
  0%|          | 0/2000 [00:00<?, ?it/s]  0%|          | 0/2000 [01:08<?, ?it/s]
Traceback (most recent call last):
  File "run_no_wandb.py", line 37, in <module>
    run_manual_configs(sweep_config)
  File "run_no_wandb.py", line 11, in run_manual_configs
    train(config)
  File "/hpcfs/users/a1787848/MRI_research/mproj7205_hpc/model/train.py", line 78, in train
    avg_loss_train = train_epoch(network, loader_train, criterion, optimizer, device, is_train=True, use_sigmoid=use_sigmoid, include_T1=include_T1)
  File "/hpcfs/users/a1787848/MRI_research/mproj7205_hpc/model/train.py", line 107, in train_epoch
    for _, data in enumerate(loader):
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 10.
Original Traceback (most recent call last):
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/hpcfs/users/a1787848/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 141, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: torch.cat(): input types can't be cast to the desired output type Int

